import type { KnownClaim } from './types';

export const KNOWN_CLAIMS: KnownClaim[] = [
  // ─── PRODUCTIVITY MYTHS ────────────────────────────────────────────────────────
  {
    id: 'habit-21-days',
    canonical: 'It takes 21 days to build a new habit',
    variants: [
      'You can form any habit in just 21 days',
      'Habits take exactly 21 days to stick',
      'After 21 consecutive days something becomes automatic',
      'The 21 day rule makes any behavior permanent',
      'Do anything for 21 days and it becomes a habit',
    ],
    category: 'productivity',
    verdict: 'misleading',
    source: 'Lally et al. (2010) found habit formation takes 18–254 days. The 21-day figure misreads Maxwell Maltz\'s observations on post-surgery adaptation.',
    campaign: 'productivity-myths',
  },
  {
    id: 'ten-thousand-hours',
    canonical: '10,000 hours of practice makes you world-class at anything',
    variants: [
      'The 10,000 hour rule guarantees mastery of any skill',
      'Malcolm Gladwell proved 10,000 hours makes anyone an expert',
      'Put in 10,000 hours of practice and you will become world class',
      'You need 10,000 hours of deliberate practice to master a skill',
      '10,000 hours is all it takes to become an expert',
    ],
    category: 'productivity',
    verdict: 'partially-false',
    source: 'Ericsson (the researcher Gladwell cited) clarified quality of deliberate practice matters far more than raw hours; mastery timelines vary by domain.',
    campaign: 'productivity-myths',
  },
  {
    id: 'multitasking-efficient',
    canonical: 'Multitasking makes you more productive and efficient',
    variants: [
      'You can get more done by doing multiple things simultaneously',
      'Multitasking is a skill that increases output',
      'Successful people multitask to save time',
      'Doing several tasks at once boosts efficiency',
    ],
    category: 'productivity',
    verdict: 'false',
    source: 'Meyer & Kieras (1997) and many follow-up studies show multitasking reduces performance by up to 40% due to task-switching cognitive costs.',
    campaign: 'productivity-myths',
  },
  {
    id: '5am-success',
    canonical: 'Waking up at 5am is the secret to success',
    variants: [
      'All successful people wake up before 5am',
      'The most productive people start their day at 4am or 5am',
      'Waking up early separates winners from losers',
      'The 5am club guarantees life-changing results',
      'Successful CEOs all wake up at 5am',
    ],
    category: 'productivity',
    verdict: 'misleading',
    source: 'Survivorship bias: only successful early risers get highlighted. Chronobiology research shows optimal wake time is highly individual.',
    campaign: 'productivity-myths',
  },
  {
    id: 'sleep-less-hustle',
    canonical: 'Successful people sleep less and work longer hours to get ahead',
    variants: [
      'You can sleep when you are dead',
      'Sleeping 4 hours gives you more time to become successful',
      'Hustle means sacrificing sleep to get ahead',
      'Successful entrepreneurs sleep only 4 to 5 hours a night',
      'Working 18 hour days is how winners outcompete everyone',
    ],
    category: 'productivity',
    verdict: 'false',
    source: 'Sleep deprivation impairs cognition, creativity, and decision-making. Most peak performers report 7–9 hours. Arianna Huffington collapsed from overwork and now advocates for sleep.',
    campaign: 'productivity-myths',
  },
  {
    id: 'success-mindset-only',
    canonical: 'Your mindset is the only thing holding you back from success',
    variants: [
      'All failure comes from having the wrong mindset',
      'Anyone can succeed if they believe hard enough',
      'The only limit you have is in your mind',
      'Change your mindset and completely change your life',
      'Poor people have a scarcity mindset that keeps them poor',
    ],
    category: 'productivity',
    verdict: 'misleading',
    source: 'Ignores systemic barriers: access to capital, quality education, healthcare, geographic opportunity, and luck all significantly shape outcomes.',
    campaign: 'productivity-myths',
  },
  {
    id: 'hard-work-always-works',
    canonical: 'Hard work always leads to success if you persist long enough',
    variants: [
      'If you work hard enough you will always succeed',
      'Successful people simply outworked everyone else',
      'Hard work beats talent every single time',
      'The only difference between success and failure is how hard you work',
      'Anyone who fails just did not work hard enough',
    ],
    category: 'productivity',
    verdict: 'misleading',
    source: 'Survivorship bias: failed hard workers are invisible. Research shows luck, timing, and structural opportunity explain a substantial variance in outcomes.',
    campaign: 'productivity-myths',
  },
  {
    id: 'millionaire-morning-routine',
    canonical: 'All millionaires and billionaires follow strict morning routines',
    variants: [
      'Every successful person has a non-negotiable morning ritual',
      'The secret to wealth is a consistent morning routine',
      'Copy a billionaire morning routine to become successful',
      'Morning routines are what separate the rich from everyone else',
    ],
    category: 'productivity',
    verdict: 'misleading',
    source: 'Cherry-picked anecdotes. Many successful people report no fixed routine. Correlation between routines and success does not establish causation.',
    campaign: 'productivity-myths',
  },
  {
    id: 'self-made-myth',
    canonical: 'Most successful entrepreneurs are entirely self-made and started from nothing',
    variants: [
      'Self-made billionaires built everything from scratch with no help',
      'Successful entrepreneurs started with nothing and built empires',
      'Anyone can be self-made if they work hard enough',
      'All great founders came from humble beginnings',
    ],
    category: 'productivity',
    verdict: 'misleading',
    source: 'Most high earners had significant advantages: family networks, access to education, inherited capital, or low-risk safety nets unavailable to most people.',
    campaign: 'productivity-myths',
  },
  {
    id: 'cold-shower-testosterone',
    canonical: 'Cold showers dramatically boost testosterone and productivity',
    variants: [
      'Taking cold showers every morning will skyrocket your testosterone',
      'Cold exposure is proven to massively increase testosterone levels',
      'Successful men all take cold showers to boost hormones',
      'Cold showers will transform your energy and focus instantly',
      'A cold shower is the ultimate productivity hack',
    ],
    category: 'health',
    verdict: 'misleading',
    source: 'Studies show minimal testosterone changes from cold exposure. A short-term norepinephrine boost exists, but "massive productivity" and hormonal claims are exaggerated.',
    campaign: 'productivity-myths',
  },
  {
    id: 'reading-books-success',
    canonical: 'Reading 50 books per year is what makes successful people successful',
    variants: [
      'All successful people read a book every week',
      'CEOs read 60 books a year and that is why they succeed',
      'Reading more books than anyone else guarantees success',
      'Average millionaires read 50 books per year and that is the difference',
    ],
    category: 'productivity',
    verdict: 'misleading',
    source: 'Survivorship bias. Many successful people read little; many avid readers are not financially successful. Reading volume likely reflects available leisure time (privilege), not a causal factor.',
    campaign: 'productivity-myths',
  },
  {
    id: 'network-is-net-worth',
    canonical: 'Your network is your net worth — who you know determines success',
    variants: [
      'Who you know is always more important than what you know',
      'Your net worth equals your network',
      'Success comes entirely from the connections you make',
      'Building the right network is the single most important thing for success',
    ],
    category: 'productivity',
    verdict: 'misleading',
    source: 'Network effects are real but the absolute framing ignores skill, quality of work, timing, and structural barriers to accessing professional networks.',
    campaign: 'productivity-myths',
  },
  // ─── HEALTH MYTHS ──────────────────────────────────────────────────────────────
  {
    id: 'vaccines-autism',
    canonical: 'Vaccines cause autism in children',
    variants: [
      'The MMR vaccine has been linked to autism',
      'Vaccine ingredients trigger autism in children',
      'There is a cover-up connecting vaccines to autism',
      'Children develop autism after receiving vaccines',
    ],
    category: 'health',
    verdict: 'false',
    source: 'The original Wakefield study was fraudulent and retracted. Dozens of large-scale independent studies find no link between any vaccine and autism.',
    campaign: 'anti-vax',
  },
  {
    id: 'sugar-hyperactivity',
    canonical: 'Sugar causes hyperactivity in children',
    variants: [
      'Sugar makes kids hyper and impossible to control',
      'Refined sugar causes ADHD-like behavior in children',
      'Candy causes hyperactive behavior in kids',
      'A sugar rush makes children act crazy',
    ],
    category: 'health',
    verdict: 'false',
    source: 'Multiple double-blind studies (Wolraich 1995, Hoover 1990) found no link between sugar and hyperactivity. The perceived effect is a psychological expectation in parents.',
  },
  {
    id: 'dietary-fat-makes-fat',
    canonical: 'Eating dietary fat makes you gain body fat and causes obesity',
    variants: [
      'Fat in food turns directly into body fat',
      'Eating fat is what causes people to become obese',
      'Low-fat diets are the best way to lose weight',
      'All fat in your diet goes straight to your waistline',
    ],
    category: 'health',
    verdict: 'misleading',
    source: 'Weight change is driven by total caloric balance. Dietary fat is not inherently fattening; refined carbohydrates and excess sugar are larger contributors in many cases.',
  },
  {
    id: 'detox-cleanse',
    canonical: 'Detox drinks and juice cleanses remove toxins from your body',
    variants: [
      'A 3-day juice cleanse will flush toxins from your liver',
      'Detox teas cleanse your digestive system and remove waste',
      'You need to detox regularly with special drinks and supplements',
      'Juice fasting removes accumulated toxins from organs',
    ],
    category: 'health',
    verdict: 'false',
    source: 'The liver, kidneys, and lymphatic system continuously remove waste products. No peer-reviewed evidence shows commercial detox products accelerate this process.',
  },
  {
    id: '8-glasses-water',
    canonical: 'Everyone must drink exactly 8 glasses of water per day for health',
    variants: [
      'You need to drink 8 cups of water daily or you will get sick',
      'The 8x8 rule: 8 glasses of 8 ounces every day is essential',
      'Drinking 2 liters of water daily is required for everyone',
      'Most people are chronically dehydrated and need to drink far more water',
    ],
    category: 'health',
    verdict: 'misleading',
    source: 'Water needs vary by body size, activity level, climate, and diet content. Heinz Valtin (2002) found no scientific basis for a universal 8-glasses-per-day rule.',
  },
  {
    id: '5g-health-danger',
    canonical: '5G wireless networks cause serious health problems and disease',
    variants: [
      '5G radiation causes cancer and other serious health issues',
      '5G towers are dangerous to human health and wellbeing',
      '5G has never been properly tested for human safety',
      '5G signals damage human cells and DNA',
    ],
    category: 'health',
    verdict: 'false',
    source: 'WHO, FDA, and multiple independent studies find no evidence that 5G radio frequencies at permitted exposure levels pose health risks.',
  },
  // ─── FINANCE MYTHS ─────────────────────────────────────────────────────────────
  {
    id: 'day-traders-lose',
    canonical: 'Over 90% of retail traders lose all their money',
    variants: [
      '95% of day traders lose money trading stocks',
      'Over 90% of people who trade stocks lose everything',
      'Nine out of ten retail investors lose money in the markets',
      'Only 5% of traders ever make consistent profit from trading',
    ],
    category: 'finance',
    verdict: 'unverified',
    source: 'Exact percentages vary widely by study, market, and methodology. Studies show 70–80% underperform indexes over time, but "lose everything" overstates results.',
    campaign: 'finance-myths',
  },
  {
    id: 'real-estate-always-up',
    canonical: 'Real estate always increases in value over the long term',
    variants: [
      'Property prices always go up if you wait long enough',
      'Real estate is the safest investment because it always appreciates',
      'You can never lose money investing in property',
      'Housing prices only ever go up over time',
    ],
    category: 'finance',
    verdict: 'misleading',
    source: 'Real estate markets have suffered major crashes (US 2008, Japan 1990s). Local markets diverge significantly; inflation-adjusted long-term returns are often modest.',
    campaign: 'finance-myths',
  },
  {
    id: 'compound-interest-guaranteed',
    canonical: 'Compound interest will make anyone wealthy if they start investing early enough',
    variants: [
      'Start investing at 20 and compound interest will make you a millionaire',
      'Albert Einstein called compound interest the eighth wonder of the world',
      'Anyone who invests consistently will become wealthy through compounding',
      'Compound interest guarantees wealth creation for patient investors',
    ],
    category: 'finance',
    verdict: 'misleading',
    source: 'Compounding is real but assumes consistent positive returns, no forced withdrawals, and ignores inflation. Most workers cannot save enough for significant compounding effects.',
    campaign: 'finance-myths',
  },
  {
    id: 'stock-market-rigged',
    canonical: 'The stock market is rigged against ordinary retail investors',
    variants: [
      'Wall Street is designed to steal money from small investors',
      'Institutional traders always front-run and exploit retail investors',
      'The stock market is a casino designed to benefit the wealthy',
      'Individual investors can never beat the institutions so should not try',
    ],
    category: 'finance',
    verdict: 'misleading',
    source: 'While institutional information advantages exist, long-term passive index investing by retail investors has historically matched or outperformed most active managers.',
    campaign: 'finance-myths',
  },
  {
    id: 'crypto-replaces-all-currency',
    canonical: 'Cryptocurrency will replace all traditional currency within the next few years',
    variants: [
      'Bitcoin will become the global reserve currency within years',
      'Crypto will make banks and governments completely obsolete',
      'Traditional money will be worthless once crypto takes over',
      'Cryptocurrency is the inevitable and imminent future of all money',
    ],
    category: 'technology',
    verdict: 'misleading',
    source: 'Cryptocurrency faces unresolved scalability, regulatory, energy, and volatility challenges. Central bank digital currencies are developing alongside crypto.',
    campaign: 'crypto-hype',
  },
  // ─── SCIENCE MYTHS ─────────────────────────────────────────────────────────────
  {
    id: 'climate-natural-cycle',
    canonical: 'Current climate change is a natural cycle and not caused by human activity',
    variants: [
      'The climate has always changed naturally so today\'s warming is just a natural cycle',
      'CO2 is not causing climate change it is part of a natural planetary cycle',
      'Climate scientists are wrong about human caused global warming',
      'Global warming is caused by the sun not human carbon emissions',
    ],
    category: 'science',
    verdict: 'false',
    source: 'Scientific consensus (97%+ of publishing climate scientists, all major IPCC reports) shows current warming rate is unprecedented and driven by human greenhouse gas emissions.',
  },
  {
    id: 'evolution-just-theory',
    canonical: 'Evolution is just an unproven theory with no real scientific evidence',
    variants: [
      'Evolution is only a theory and not a proven fact',
      'There is no real evidence for the theory of evolution',
      'Scientists cannot actually prove that evolution happened',
      'Evolution has never been directly observed or properly verified',
    ],
    category: 'science',
    verdict: 'false',
    source: 'In science a "theory" is a rigorously tested explanatory framework. Evolution is supported by fossil records, genetics, directly observed speciation, and comparative anatomy.',
  },
  // ─── TECHNOLOGY MYTHS ──────────────────────────────────────────────────────────
  {
    id: 'ai-all-jobs-soon',
    canonical: 'AI will replace all human jobs within the next 5 years',
    variants: [
      'Artificial intelligence will make all workers unemployed very soon',
      'AI is going to eliminate most jobs within 5 years',
      'Within 5 years AI will replace everything humans do for work',
      'Your job will not exist in 5 years because of artificial intelligence',
    ],
    category: 'technology',
    verdict: 'misleading',
    source: 'Economists find AI primarily automates tasks within jobs rather than entire occupations. Historical technology transitions also created new job categories. Timelines are highly contested.',
    campaign: 'ai-hype',
  },
  {
    id: 'social-media-causes-depression',
    canonical: 'Social media use directly causes depression and mental health disorders',
    variants: [
      'Using social media makes you depressed',
      'Instagram directly causes teen depression',
      'Facebook is scientifically proven to cause mental illness',
      'Social media use is directly linked to depression rates in young people',
    ],
    category: 'technology',
    verdict: 'partially-false',
    source: 'Correlational studies exist but causation is disputed. Heavy passive consumption correlates with lower wellbeing; active use shows weaker effects. Individual predisposition matters significantly.',
  },
  // ─── SOCIAL MYTHS ──────────────────────────────────────────────────────────────
  {
    id: 'poverty-laziness',
    canonical: 'Poor people are poor because they do not work hard enough or make poor decisions',
    variants: [
      'Poverty is the result of laziness and bad personal decisions',
      'If poor people worked harder they would not be poor',
      'Rich people are rich simply because they work harder than poor people',
      'Anyone can escape poverty through hard work and determination alone',
    ],
    category: 'social',
    verdict: 'misleading',
    source: 'Structural factors including quality of early education, healthcare access, geographic opportunity, generational wealth, and discrimination strongly predict economic outcomes independent of work ethic.',
    campaign: 'productivity-myths',
  },
  {
    id: 'anyone-can-be-millionaire',
    canonical: 'Anyone can become a millionaire with the right mindset and habits',
    variants: [
      'Every person has an equal chance to become a millionaire',
      'Wealth is available to anyone willing to adopt the right habits',
      'The only thing separating you from being a millionaire is mindset',
      'Millionaire status is achievable for literally anyone',
    ],
    category: 'social',
    verdict: 'misleading',
    source: 'Wealth accumulation is heavily influenced by starting conditions: inherited assets, parental education, social networks, and access to healthcare and quality schooling.',
    campaign: 'productivity-myths',
  },
];
